# Generated by Django 3.0.7 on 2020-06-24 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('charges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
